# Generated by Django 2.2.5 on 2019-09-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=500)),
                ('user_name', models.CharField(max_length=50)),
                ('signup_date', models.DateField(blank=True, null=True)),
                ('user_info', models.TextField()),
                ('subscribers_count', models.IntegerField(default=0)),
            ],
        ),
    ]
